/**
 * generated by Xtext 2.25.0
 */
package org.xtext.example.mydsl.formatting2;

import com.google.inject.Inject;
import java.util.Arrays;
import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.formatting2.AbstractFormatter2;
import org.eclipse.xtext.formatting2.IFormattableDocument;
import org.eclipse.xtext.resource.XtextResource;
import org.eclipse.xtext.xbase.lib.Extension;
import org.xtext.example.mydsl.services.MyDslGrammarAccess;
import programChartSawsen.Functions;
import programChartSawsen.ProgChart;

@SuppressWarnings("all")
public class MyDslFormatter extends AbstractFormatter2 {
  @Inject
  @Extension
  private MyDslGrammarAccess _myDslGrammarAccess;
  
  protected void _format(final ProgChart progChart, @Extension final IFormattableDocument document) {
    EList<Functions> _functions = progChart.getFunctions();
    for (final Functions functions : _functions) {
      document.<Functions>format(functions);
    }
  }
  
  public void format(final Object progChart, final IFormattableDocument document) {
    if (progChart instanceof XtextResource) {
      _format((XtextResource)progChart, document);
      return;
    } else if (progChart instanceof ProgChart) {
      _format((ProgChart)progChart, document);
      return;
    } else if (progChart instanceof EObject) {
      _format((EObject)progChart, document);
      return;
    } else if (progChart == null) {
      _format((Void)null, document);
      return;
    } else if (progChart != null) {
      _format(progChart, document);
      return;
    } else {
      throw new IllegalArgumentException("Unhandled parameter types: " +
        Arrays.<Object>asList(progChart, document).toString());
    }
  }
}
