<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="programChartSawsen" nsURI="http://www.example.org/programChartSawsen"
    nsPrefix="programChartSawsen">
  <eClassifiers xsi:type="ecore:EClass" name="ApplyFilter" eSuperTypes="#//Functions">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="columname" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="filter" eType="#//FilterType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="filtervalue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="filteredoutput" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CreateChart" eSuperTypes="#//Functions">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="chart" eType="#//ChartType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="xlabel" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ylabel" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="titlechart" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CsvLoader" eSuperTypes="#//Functions">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="path" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ChartType">
    <eLiterals name="histogram"/>
    <eLiterals name="pie" value="1"/>
    <eLiterals name="line" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="FilterType">
    <eLiterals name="inf"/>
    <eLiterals name="sup" value="1"/>
    <eLiterals name="equal" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Functions" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="ProgChart">
    <eStructuralFeatures xsi:type="ecore:EReference" name="functions" lowerBound="1"
        upperBound="-1" eType="#//Functions" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SelectedColumns" eSuperTypes="#//Functions">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="columnsname" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="outputpath" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
